### ISSUE TITLE
Progress?

### ISSUE THREAD

**Issue by QAnders** [Sagacify/sqs-move#19]
Exactly what I needed, thanks!

Would it be possible to include some progress, e.g. https://www.npmjs.com/package/cli-progress for running in CLI?

I'd created a "app" that is using the `inquirer` lib to ask which queues, etc. and after that is done I use your lib to do the actual moving but a status would be nice to be able to log out... :) 

A very "simplistic" progress could be like:
```
// Get the queue depth prior to starting
const qDepth = await sqsInstance.getQueueAttributes({
        QueueUrl: receiveOptions.QueueUrl,
        AttributeNames:['ApproximateNumberOfMessages']
    }).promise()
    .then(data => {
        return data && data.Attributes && data.Attributes.ApproximateNumberOfMessages ? data.Attributes.ApproximateNumberOfMessages : 0;
    });
```

```
// Write out the count to stdout:
    process.stdout.cursorTo(0);
    process.stdout.clearLine();
    process.stdout.cursorTo(0);
    process.stdout.write(`moving ${movedCount} of ${qDepth}`);
```

This works and writes the line to the terminal but some property to use it or not would be good of course!

**Comment by OlivierCuyp** [comment]
@QAnders thanks for your interest.
We use this server side on our apps, so we don't want to `console.log` on the server.
IMHO npm package should never log, since the way of logging belongs to each app & context.
But I understand your concerns, so what I can propose is to add a hook "progress" called on after batch of messages.
This would be usable like this:

```js
const { movedCount } = await sqsMove(
  sqsInstance,
  'https://sqs.eu-west-1.amazonaws.com/123456789012/some-dead-letter-queue',
  'https://sqs.eu-west-1.amazonaws.com/123456789012/some-process-queue',
  {
    "progress": (messagesIds) => {
      // your code to log what ever you like (e.g. console.log(`Messages treated ${messageIds.length}`))
    }
  }
);
```

Just a warning calling each time `getQueueAttributes` might slow down the transfer...
Let me know if this would be ok for you.

**Comment by OlivierCuyp** [comment]
Closing this issue since we didn't get any answer
